### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/redis#16]
- [x] 2 CPU
- [x] CPU affinity
- [x] More instance types
- [x] 1cpu vs 2cpu

**Comment by hlwanghl** [comment]
# 基准测试

主机类型：
主机内存：
测试机类型：
测试机内存：

版本 | 4.0 | 5.0（单核）| 5.0（双核）
-- | -- | -- | --
QPS | x | x | x
CPU（页面）| x | x | x
CPU（top）| x | x | x

**Comment by hlwanghl** [comment]
# CPU 使用率测试

主机类型：
主机内存：
测试机类型：
测试机内存：

版本 | 5.0（单核）
-- | --
CPU（页面）| x
CPU（top）| x

**Comment by MrYourM** [comment]
# 基准测试

主机类型：基础型 4C 
主机内存：4G
测试机类型：基础型
测试机内存：1G

版本 | 4.0 | 5.0（单核）| 5.0（双核）
-- | -- | -- | --
QPS GET | 42918.46 | 46125.46 | 55157.20
QPS SET | 46210.72 | 50125.31 | 53504.55
CPU（页面）| 70-89 | 98 | 57
CPU（top）| 70-89 | 50-60 | 50-60
