### ISSUE TITLE
改从 sentinel 获取主节点信息

### ISSUE THREAD

**Issue by hlwanghl** [QingCloudAppcenter/redis#4]
https://github.com/QingCloudAppcenter/redis/blob/master/ansible/roles/redis-standalone/files/opt/app/bin/node/redis-standalone.sh#L95

目前是通过 sentinel 落盘的文件获取的，这种方法可能会在 sentinel 进程意外退出的时候有潜在问题，可以改为直接从 sentinel 获取实时信息，比如以下命令：

`redis-cli -p 26379 sentinel get-master-addr-by-name master`

**Comment by MrYourM** [comment]
修改为从sentinel 获取会导致重启集群出现三从
