### ISSUE TITLE
【redis cluster】保存配置参数后，节点实时角色中信息显示不正确

### ISSUE THREAD

**Issue by liuyp2018** [QingCloudAppcenter/redis#55]
修改配置参数后保存，查看节点实时角色中信息显示不正确
ip 角色 对应主节点ip项显示信息分别为：
redis is loadingt

**Comment by MrYourM** [comment]
该情况出现在redis 节点数据较多的时候，redis 重启后加载数据到内存时对任意命令的回复均为 loading the dataset in memory

**Comment by liuyp2018** [comment]
问题已修复，关闭问题。
