### ISSUE TITLE
【redis cluster】节点磁盘占满后，切换网络失败

### ISSUE THREAD

**Issue by liuyp2018** [QingCloudAppcenter/redis#59]
节点磁盘占满后，进行切换网络操作，会报切换网络失败错误；
此时，查看集群所在网络已切换，但节点ip有时会切换，有时未切换。

**Comment by MrYourM** [comment]
该情况达到预期，即在非正常情况下，切换私网不允许继续进行，如果出现问题，则终止切换过程
