### ISSUE TITLE
getClusterMatched 函数少处理一种情况

### ISSUE THREAD

**Issue by MrYourM** [QingCloudAppcenter/redis#96]
[关键位置](https://github.com/QingCloudAppcenter/redis/blob/master/ansible/roles/redis-cluster/files/opt/app/bin/node/redis-cluster.sh#L566) 对于从文件 nodes-6379.conf 中读取内容的过滤不够详尽容易引起误判

需要改为
```
if [[ "$(echo "$clusterNodes" |grep -Ev "$myClusterIps" |grep -v "Epoch")" =~ [a-z0-9]+ ]];then
```

**Comment by hlwanghl** [comment]
Fixed by #111
