### ISSUE TITLE
备份超时

### ISSUE THREAD

**Issue by MrYourM** [QingCloudAppcenter/redis#98]
有用户备份 12.88GB 数据超时，可能为数据粒度比较小，数据个数比较多造成生成 rdb 文件耗时较长

处理方式：

https://github.com/QingCloudAppcenter/redis/blob/master/ansible/roles/redis-standalone/files/opt/app/bin/node/redis-standalone.sh#L345
该位置代码做下修改
```
retry 60 3 $EC_BACKUP_ERR checkBgsaveDone $lastTime 
```

**Comment by hlwanghl** [comment]
3 分钟够吗？不够可以再加点。

**Comment by MrYourM** [comment]
这个之后我再测试下，1条数据 1kb，压 64GB 数据看下耗时

**Comment by MrYourM** [comment]
每个数据 3 字节，共 49.42G 数据，bgsave 共耗时 859s，按照 60 GB 计算，外加 120s 的 buffer，最终 timeout 设置为 1151s
