### ISSUE TITLE
防止集群互串引发的 bug

### ISSUE THREAD

**Issue by MrYourM** [QingCloudAppcenter/redis#99]
app: redis cluster 
情况：主节点被迁移后，由于从节点变为了主节点，导致原主节点无法起来
处理方式：

![image](https://user-images.githubusercontent.com/44762341/95005239-330ed280-0628-11eb-93f6-80cc7b0577a9.png)

**Comment by MrYourM** [comment]
https://github.com/QingCloudAppcenter/redis/blob/master/ansible/roles/redis-cluster/files/opt/app/bin/node/redis-cluster.sh#L565 改为如下即可
```
myClusterIps="${myClusterIps%|*}|Epoch)"
```

**Comment by hlwanghl** [comment]
> https://github.com/QingCloudAppcenter/redis/blob/master/ansible/roles/redis-cluster/files/opt/app/bin/node/redis-cluster.sh#L565 改为如下即可
> 
> ```
> myClusterIps="${myClusterIps%|*}|Epoch)"
> ```

这种情况下 nodes-6379.conf 内容是什么样？这段代码是判断有无集群外的 IP 混进来，不是一回事吧。

**Comment by MrYourM** [comment]
conf 文件比 cluster nodes 多了一个 var Epoch 类的信息，过滤掉就好了

**Comment by hlwanghl** [comment]
> conf 文件比 cluster nodes 多了一个 var Epoch 类的信息，过滤掉就好了

最后多一行是吧？过滤尽量准确一些，不要把正常的行误删。

**Comment by MrYourM** [comment]
嗯
